services:
    api:
        hostname: api
        build: ./API
        ports:
            - 8080:8080
        environment:
            - spring.profiles.active=prod
            - cors.origin=http://localhost:3000
            - algolia.application_id=3VJL1MLU0K
            - algolia.api_key=fuckyouandthehorseyourodeinon
        depends_on:
            db:
                condition: service_healthy

    ui:
        hostname: ui
        build: ./UI
        ports:
            - 3000:3000
        environment:
            - SERVER_BACKEND_URL=http://api:8080
            - SERVER_FRONTEND_URL=http://localhost:8080
            - NODE_ENV=dev

    db:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 2s
            retries: 5
