services:
    api:
        hostname: api
        build: ./API
        ports:
            - 8080:8080
        environment:
            - spring.profiles.active=prod
        env_file:
            - API.env
        depends_on:
            db:
                condition: service_healthy

    ui:
        hostname: ui
        build:
            context: ./UI
            args:
                - SERVER_BACKEND_URL=http://api:8080
        env_file:
            - UI.env
        ports:
            - 3000:3000

    db:
        image: postgres:9.6
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 2s
            retries: 5
        volumes:
            - ./data/postgres:/var/lib/postgresql/data
