algolia:
    application_id: ${ALGOLIA_APPLICATION_ID}
    api_key: ${ALGOLIA_API_KEY}
sendgrid:
    api_key: ${SENDGRID_API_KEY}
    from: ${SENDGRID_FROM_EMAIL}

---
spring:
    config:
        activate:
            on-profile:
                - dev
                - test
    h2:
        console:
            enabled: true

    jpa:
        show-sql: true
        hibernate:
            ddl-auto: none

        properties:
            hibernate:
                dialect: org.hibernate.dialect.H2Dialect
        generate-ddl: false
    sql:
        init:
            mode: never
            platform: h2
jwt:
    secret: someveryveryveryveryveryveryverylongsecretorsomethingihavenoideaman
    expiration: 900000 # 15 minutes
default-manager:
    username: manager
    password: manager
---
spring:
    config:
        activate:
            on-profile:
                - test
    flyway:
        url: jdbc:h2:mem:lepine;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
        baseline-on-migrate: true
        user: sa
        password:

    datasource:
        url: jdbc:h2:mem:lepine;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
        username: sa
        password:
        hikari:
            initialization-fail-timeout: 60000

sendgrid:
    api_key: fake.api.key
    from: fake@email.com
cors:
    origin: http://some.fake.url
---
spring:
    config:
        activate:
            on-profile:
                - dev
    flyway:
        url: jdbc:h2:file:./lepine;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
        baseline-on-migrate: true
        user: sa
        password:

    datasource:
        url: jdbc:h2:file:./lepine;DATABASE_TO_UPPER=false;CASE_INSENSITIVE_IDENTIFIERS=TRUE;DB_CLOSE_DELAY=-1
        driver-class-name: org.h2.Driver
        username: sa
        password:
        hikari:
            initialization-fail-timeout: 60000
cors:
    origin: http://localhost:3000

---
spring:
    config:
        activate:
            on-profile:
                - prod
    flyway:
        url: ${DATABASE_URL:jdbc:postgresql://db:5432/}
        baseline-on-migrate: true
        user: postgres
        password: postgres
    datasource:
        url: ${DATABASE_URL:jdbc:postgresql://db:5432/}
        driver-class-name: org.postgresql.Driver
        username: postgres
        password: postgres
        hikari:
            initialization-fail-timeout: 60000
cors:
    origin: ${CORS_ORIGIN:none}
